# Generated by Django 3.2.23 on 2024-01-11 12:11

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_google_maps.fields
import user.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
            ],
            options={
                'verbose_name_plural': 'Manage Users',
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'Modules',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Devotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='devotion_photos/')),
                ('Theme', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('scripture', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Devotion',
                'verbose_name_plural': 'Devotions',
            },
        ),
        migrations.CreateModel(
            name='DonationCause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('deadline', models.DateField()),
                ('contacts', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number with country code. Example: +123456789', regex='^\\+(\\d{1,15})$')])),
                ('details', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Donation Cause',
                'verbose_name_plural': 'Donation Cuase',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('contact', models.CharField(max_length=255)),
                ('address', django_google_maps.fields.AddressField(max_length=200)),
                ('geolocation', django_google_maps.fields.GeoLocationField(max_length=100)),
                ('remaining_days', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Event Detail',
                'verbose_name_plural': 'Event Details',
            },
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministry_name', models.CharField(max_length=25)),
                ('ministry_photo', models.ImageField(blank=True, null=True, upload_to='ministry_photos/')),
                ('ministry_goal', models.TextField(blank=True)),
                ('ministry_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecentSermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('preacher', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='recent_sermon_photos/')),
            ],
            options={
                'verbose_name': 'Recent Sermon',
                'verbose_name_plural': 'Recent Sermons',
            },
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='uploadedimage',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='uploadedimage',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(upload_to=user.models.get_image_upload_path),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to=settings.AUTH_USER_MODEL),
        ),
    ]
