# Generated by Django 3.2.23 on 2024-01-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20240111_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisit',
            name='counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
