# Generated by Django 5.0.1 on 2024-01-12 07:18

import django_google_maps.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_event_address_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='addresss',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=django_google_maps.fields.AddressField(max_length=200),
        ),
    ]
