# Generated by Django 5.0.1 on 2024-01-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_event_addresss_alter_event_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='addresss',
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
