# Generated by Django 5.0.1 on 2024-01-22 14:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_devotion_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recentsermon',
            options={'verbose_name': 'Gospel', 'verbose_name_plural': 'Gospel Word'},
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recentsermon',
            name='short_description',
            field=models.TextField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='contact',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='ministry_goal',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recentsermon',
            name='preacher',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='recentsermon',
            name='theme',
            field=models.CharField(max_length=40),
        ),
    ]
