# Generated by Django 5.0.1 on 2024-07-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_trafficdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitevisit',
            name='counter',
            field=models.IntegerField(default=1),
        ),
    ]
