# Generated by Django 5.0.1 on 2024-07-06 03:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_sitevisit_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.URLField(default=django.utils.timezone.now, verbose_name='Google Form Link'),
            preserve_default=False,
        ),
    ]
